version: 2

project_name: yeager

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: yg
    main: ./cmd/yeager/
    binary: yg
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "yeager_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^_dev:"
      - "^wip"

release:
  github:
    owner: gridlhq
    name: yeager
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
