package config

// Template is the commented .yeager.toml generated by `yg init`.
// All values are commented out — users uncomment what they want to change.
const Template = `# .yeager.toml
# generated by yeager -- all values below are defaults, uncomment to override

# ── compute ──────────────────────────────────────────────────────
# VM size and AWS region.

[compute]
# size = "medium"             # small (2cpu/4gb) | medium (4cpu/8gb)
                              # large (8cpu/16gb) | xlarge (16cpu/32gb)
# region = "us-east-1"        # AWS region (default: closest to you)

# ── lifecycle ────────────────────────────────────────────────────
# How long before the VM stops, gets terminated, and gets deleted.

[lifecycle]
# grace_period = "2m"         # wait this long after a command finishes
                              # before auto-stopping the VM (keeps it
                              # "warm" for quick follow-up commands)
# idle_stop = "10m"           # stop VM after this much idle time
# stopped_terminate = "7d"    # terminate stopped VM after this long
# terminated_delete_ami = "30d"  # delete saved AMI snapshot after this long

# ── setup ────────────────────────────────────────────────────────
# Extra system packages and commands to run when the VM is created.
# Language toolchains (Rust, Node, Go, etc.) are auto-detected --
# this is for things auto-detection can't know about.
# Runs once on VM creation, and again if this section changes.

[setup]
# packages = ["libpq-dev", "chromium-browser"]
# run = [
#   "npx playwright install --with-deps",
#   "cargo install cargo-nextest",
# ]

# ── sync ─────────────────────────────────────────────────────────
# Override file sync behavior. yeager syncs your project to the VM
# before each run, respecting .gitignore plus sensible defaults
# (node_modules, target, .git, __pycache__, etc.).

[sync]
# include = ["fixtures/large-dataset.bin"]  # sync files .gitignore skips
# exclude = ["data/", "logs/"]              # skip extra paths

# ── artifacts ────────────────────────────────────────────────────
# Paths on the VM to upload to S3 after each run.
# stdout/stderr are always saved. This is for extra files like
# coverage reports, test results, screenshots, etc.

[artifacts]
# paths = ["coverage/", "test-results/", "playwright-report/"]
`
